version: "3.8"
services:
  service-one:
    container_name: service-one
    image: lottery/service-one:latest
    build: ./service_one 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  service-two:
    container_name: service_two
    image: lottery/service_two:latest
    build: ./service_two 
    ports:
    - target: 5002
      protocol: tcp
  service-three:
    container_name: service_three
    image: lottery/service_three:latest
    build: ./service_three 
    ports:
    - target: 5003
      protocol: tcp
  service-four:
    container_name: service_four
    image: lottery/service_four:latest
    build: ./service_four 
    ports:
    - target: 5001
      protocol: tcp

