version: "3.8"
services:
  service-one:
    container_name: service-one
    image: service-one:latest
    build: ./services-one 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service-two:
    container_name: service-two
    image: service-two:latest
    build: ./services-two 
    ports:
    - target: 5002
        protocol: tcp
  service-three:
    container_name: service-three
    image: service-three:latest
    build: ./ervices-three 
    ports:
    - target: 5003
      protocol: tcp
  service-four:
    container_name: service-four
    image: service-four:latest
    build: ./services-four 
    ports:
    - target: 5001
    protocol: tcp
    environment: 
    DATABASE_URI: ${DATABASE_URI}
  # nginx:
  #   image: nginx:latest
  #   ports:
  #   - target: 80
  #     published: 80
  #     protocol: tcp
  #   volumes:
  #   - type: bind
  #     source: ./nginx/nginx.conf
  #     target: /etc/nginx/nginx.conf