version: "3.8"
services:
  service-one:
    container_name: service-one
    image: faidarus/service-one:latest
    build: ./service-one 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  service-two:
    container_name: service-two
    image: faidarus/service-two:latest
    build: ./service-two 
    ports:
    - target: 5002 
      protocol: tcp 
  service-three:
    container_name: service-three
    image: faidarus/service-three:latest
    build: ./service-three 
    ports:
    - target: 5003
      protocol: tcp
  service-four:
    container_name: service-four
    image: faidarus/service-four:latest
    build: ./service-four 
    ports:
    - target: 5001
      protocol: tcp

