pipeline{
        agent any
        stages{
            stage('Build'){
                steps{
                    script{
                        image = docker.build("service-one")
                        image = docker.build("service-two")
                        image = docker.build("service-three")
                        image = docker.build("service-four")
                    }
                }
            }
            stage('Tag & Push Image'){
                steps{
                        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials'){
                                image.push("${env.app_version}")
                        }
                    }
                }
            }
            stage('Deploy App'){
                steps{
                    sh "docker-compose pull && docker-compose up -d && docker stack deploy --compose-file docker-compose.yaml main-services"
                }
            }
        }
}